### ISSUE TITLE
No glue.py in scripts.

### ISSUE THREAD

**Issue by KKBhatt17** [ZhangHaojie077/DPS#1]
Line number 244 in run_trainer.py:
datasets = load_dataset("glue.py", data_args.task_name)

But there is no file named glue.py there in scripts. How to resolve this?

**Comment by ZhangHaojie077** [comment]
Hi, you can get "glue.py" at the following link: https://github.com/huggingface/transformers/blob/v4.7.0/src/transformers/data/datasets/glue.py
